### ISSUE TITLE
Inconsistent output between mac and other OSs

### ISSUE THREAD

**Issue by finnbear** [sobotka/filmic-blender#49] opened 2018-11-03 01:15 UTC
**Background:**
I rendered a project on the sheep-it renderfarm, which spread the load over machines with all three major OSs: Linux, Windows, and Mac.

- Blender: v2.79b
- Filmic: Whatever version sheep-it uses in conjunction with that blender version
- Compositing: Yes

**Issue:**
The frames rendered with MacOS were slightly darker than the frames rendered with the other OSs, Linux and Windows.

**Images:**
Not rendered/composited on Mac:
![image](https://user-images.githubusercontent.com/20015102/47946636-8a9be500-decb-11e8-9e12-c84a759088e2.png)

Rendered/composited on Mac:
![image](https://user-images.githubusercontent.com/20015102/47946644-a8694a00-decb-11e8-9758-c9478c375dac.png)

**Other notes:**

- The machines were mostly Xeon W or Xeon E
- I can't be 100% sure that filmic is causing the issue

**Comment by sobotka** [comment] 2018-11-03 16:39
There isn’t enough information in this post to make any useful inferences.

There haven’t been reports of transfer function differences such as what you are reporting, which indicates the issue _may_ be in your files.

When trying to diagnose these issues, file format encodings, operating systems, and hardware all play a role.

Best advice is to encode to EXR then compare output. Then compare file formats.

I’ll close this for now until you are able to provide more in-depth analysis.

**Closed by sobotka** 2018-11-03 16:39 UTC

**Comment by finnbear** [comment] 2018-11-03 17:03
Ok, I understand. Unfortunately, sheepit doesn't support openexr so that isn't an option at the moment. I will tell you if I collect more useful information in the future :)

**Comment by sobotka** [comment] 2018-11-03 21:02
I am interested in this, to see if there is an issue somewhere in the pipeline. If you can't save a baseline EXR (what!?) then you'll have to try other formats. Compare against a 16 bit TIFF and 16 bit (ugh) PNG. If you can save as the Base Log Encoding, save it, download it, and apply the Looks locally.

Also, remove anything and everything out of your node chain to see if the problem is somewhere in there. Hard to know what might be causing it.

If there is an issue, it would be good to sort it out and get it fixed, even if it isn't part of Filmic.

**Comment by finnbear** [comment] 2018-11-04 06:45
Thanks for the advice! When you say to compare TIFF vs PNG, would that be on a Linux machine, a Mac, or both? Applying the looks locally would probably work, but it would take too much time for my projects.

When I'm done with my current project, I will test a simple scene on my own mac and linux computers. This will help distinguish between common sheepit dark frame issues and filmic issues.
